server {
    listen 80;
    server_name fazmarket.3il-rodez-projets.site;

    # redirection HTTP → HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name fazmarket.3il-rodez-projets.site;

    ssl_certificate /etc/letsencrypt/live/fazmarket.3il-rodez-projets.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/fazmarket.3il-rodez-projets.site/privkey.pem;

    location / {
        proxy_pass http://frontend:80;
    }

    location /api/products/ {
        proxy_pass http://product-service:8080/api/products/;
    }

    location /api/cart/ {
        proxy_pass http://cart-service:8000/api/cart/;
    }
}