server {

    listen 80;

    server_name fazmarket.3il-rodez-projets.site;

    location / {
        proxy_pass http://frontend:80;
    }

    location /api/products/ {
        proxy_pass http://product-service:8080/;
    }

    location /api/cart/ {
        proxy_pass http://cart-service:8000/;
    }
}